name: HiveHoney
title: "HiveHoney Dev Blog"
description: "Java, Spring, algorithms, and daily life notes."
tags:
  - blog
  - development
  - java
  - spring
  - spring-boot
  - algorithm
  - coding-test
  - backend
  - programming
  - daily
  - diary
  - korea
language: "en"
languages:
  - en
  - ko
show_hero: true
menu:
  - title: Home
    url: /
  - title: About
    url: /about
  - title: Contact
    url: /contact
  - title: Feed
    url: /feed.xml
email: hive0917@gmail.com
# See: https://disqus.com/
disqus_username: disqus_username
# Contact Form Setting
# See: https://formspree.io/
formspree_form_id: formspree_form_id
